//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemExtra
    {
        public int ItemId { get; set; }
        public int ExtraId { get; set; }
    }
}
